### PR TITLE
Added saving

### PR DESCRIPTION
**Pull request by hotdropper**
Feel free to either merge or leave it open -- playing with stuff now that I got the serial console working :)

### CODE REVIEW

**Comment by hotdropper** [comment]
auth is mostly in... there's a little 'this' weirdness though i think

**Comment by hotdropper** [comment]
I've started trying to pull this all apart into a more 'edit friendly' setup...

https://github.com/hotdropper/puck-js-ntag-emulation

should handle doing packaging and minification and such...

**Comment by DanTheMan827** [comment]
I haven't actually tested this, but the only thing I'd be concerned about is the logging adding too much of a delay to the point that iOS is no longer happy to read/write to the puck... 

If it is in fact because of something else like a CRC not being sent that would be wonderful, I don't really have any hardware that I can access at a low enough level to test that though... the other thing to test would be the timings

I wonder if maybe sending ACK before calling the relevant command function would work or if it would be completely against the spec?

I started with the [original NFC code from the espruino modules directory](https://www.espruino.com/modules/NFCTag.js) and the length of the RX callback seemed to be causing issues, I'm assuming it's because the function is parsed every time it's called

If I were to take my existing code and put it into a single callback with a switch statement iOS would not accept it for whatever reason.

The other thing I'm not so sure about is the number of write cycles the flash has, my original code was set to write the file every time the NFC disconnected if the puck was written in that session but I commented that out because of those concerns and the fact that the battery should last about 1 year give or take.

The password implementation seems good, but I'd probably clear the relevant pages on disconnect, maybe even just check inside the write command which page is being written to and handle it in there.

**Comment by jmather** [comment]
### Logging 

So the logging was built specifically with that in mind.. by default it is off, but if you log into the console, and run `startNFMonitor()` then it kicks on, and starts checking every 5 seconds (could even be an argument to `startNFMonitor` really) for new logs, and displaying them.

The next tweak to logging will make the rc/tx wrappers bump a 'wrote recently' and then the 5 second timeout would have two phases... phase 1 is 'is wrote recently true? set it to false and exit.', and then if it's false, when it runs next time, it'll do the rest of the logic for displaying the logs.

Essentially designed to be as non-invasive as possible. Logs get pushed into the temp array after-the-fact (so first all logic for responses is handled) and nothing is written to the console until it's pretty sure it's in a quiet period.

### Handling commands

For handling the command commands, I think you have the right idea in place -- a switch was not going to cut it in terms of the speed required, since we in general have about 5ms to respond, so using a decision tree is the right way to go.

It's probably worth even duplicating some code refs to expand out the decision tree to [command][authenticated?][backdoored?].

You *should* be ok to send an ACK whenever... or you could just make a 'puckAck' command -- have it just retry on failure instead of bombing out -- and then you know you have a way to 'rate limit' if you're writing too fast.

In general, I think the idea is going to be that you want to push as much of the work 'forward' or 'backward' as possible. For example, I added the _initCard() as a step when constructing the tag that is responsible for pulling out the PWD and PACK from the data, so we don't even have to spend time searching the data for it. 

I suspect in all but very extreme edge cases, processing the 'locked' stuff will be fine to handle 'on session close' as well, which is the route I'm going with my little refactor project, as I suspect most 'real world' uses aren't going to have a lot of checks like 'well, what if i write to this protected area and read from it immediately after that write'.

### Write cycles

I think in general flash gets 10,000 write cycles, and the chips have logic in them to spread the writes out over the space available... marking 'deleted' as 'dirty' until such a time where it needs more space than is 'free' at which point it starts over again.

Running off of battery, yeah, the writes are less critical, but right now I'm wired up to hard-line power w/ serial, and having to re-write the tag every time in order to read from it kinda sucks :D

### password stuff

Yeah... I've been pondering on the whole write-protected thing and the logic and timing and such.... which lead me to my conclusions above that I *think* it's probably ok to just process the write-protection when the authenticated (or backdoored) session closes. 5ms isn't a lot of time for logic to be involved.

Probably the best solution that is most compatible is another logic tree for writes which has the /bits/ for the write locks and the bytes for the pages, and you set it either to do the write (or partial write in the case of page 2 to write the lock bytes), or to respond with the write-lock NAK, and so your write 'command' just ends up being something like `this.writeBlock[rx[1]](rx]);`

**Comment by hotdropper** [comment]
Notable changes: I found a bit of a leak/performance issue in how the NRF.on()'s were attaching -- they persist between off/on calls, so with the way I had the code flowing, it was just piling more and more of them on...

Also, experimenting with the NDEF writer you mentioned on Reddit, the logging code does add just enough overhead that it causes some issues, even just being there... the app crashes when i try to format after calling `NFCLogger.attach(NRF)` (which ... i dunno, that's pretty awesome, I can crash an app from being too slow? really? lol...).

They do have their `"compiled";` thing that I want to play with some though, as I bet in some circumstances it could give some great performance enhancements, but you lose the boost when you reach outside of your immediate context, so it's going to take some restructuring to make beneficial.

**Comment by DanTheMan827** [comment]
If you're still interested in this, I've just built the NTAG215 emulation into the firmware and now just use javascript for the bluetooth and basic logic.

**Comment by Swordstone86** [comment]
dan the MAN truly

**Pull request closed without merging**
